# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   annotations:
#     deployment.kubernetes.io/revision: "2"
#     kubectl.kubernetes.io/last-applied-configuration: |
#       {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"nginx"},"name":"nginx-deployment","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"nginx"}},"template":{"metadata":{"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx:1.16","name":"nginx","ports":[{"containerPort":8080}]}]}}}}
#   creationTimestamp: "2024-11-29T04:36:25Z"
#   generation: 4
#   labels:
#     app: nginx
#   name: nginx-deployment
#   namespace: default
#   resourceVersion: "27815"
#   uid: 9eaee8fd-77f0-4be4-a4dc-f6661312cc18
# spec:
#   progressDeadlineSeconds: 600
#   replicas: 2
#   revisionHistoryLimit: 10
#   selector:
#     matchLabels:
#       app: nginx
#   strategy:
#     rollingUpdate:
#       maxSurge: 25%
#       maxUnavailable: 25%
#     type: RollingUpdate
#   template:
#     metadata:
#       creationTimestamp: null
#       labels:
#         app: nginx
#     spec:
#       containers:
#       - image: nginx:1.16
#         imagePullPolicy: IfNotPresent
#         name: nginx
#         ports:
#         - containerPort: 8080
#           protocol: TCP
#         resources: {}
#         terminationMessagePath: /dev/termination-log
#         terminationMessagePolicy: File
#       dnsPolicy: ClusterFirst
#       restartPolicy: Always
#       schedulerName: default-scheduler
#       securityContext: {}
#       terminationGracePeriodSeconds: 30
# status:
#   availableReplicas: 2
#   conditions:
#   - lastTransitionTime: "2024-11-29T04:36:25Z"
#     lastUpdateTime: "2024-11-29T05:16:58Z"
#     message: ReplicaSet "nginx-deployment-55495bf96d" has successfully progressed.
#     reason: NewReplicaSetAvailable
#     status: "True"
#     type: Progressing
#   - lastTransitionTime: "2024-11-29T05:19:26Z"
#     lastUpdateTime: "2024-11-29T05:19:26Z"
#     message: Deployment has minimum availability.
#     reason: MinimumReplicasAvailable
#     status: "True"
#     type: Available
#   observedGeneration: 4
#   readyReplicas: 2
#   replicas: 2
#   updatedReplicas: 2
